apiVersion: ENC[AES256_GCM,data:T1Q=,iv:x/+VgrRJi7ICRcHa9fsXsVNcTvmldoBEmDLpRp0Ryhw=,tag:p73jebMnCEgp+zRMNDG0CA==,type:str]
kind: ENC[AES256_GCM,data:Q1JLBevc,iv:aI0yRES5sus2mOPtsJhZ0sZHIPmW8qPn6a07JtFtDgw=,tag:rvNZJZ/60OoWZB+K7q8Rew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:R11R1VRJVatU1gK+rh5apHPxhzk=,iv:ICE0HEyThC8pdfcWzhIqK8NQ6QsUECRFMwonFtIEd9E=,tag:n18gQg88Sn6IV6vWoJeqEg==,type:str]
    namespace: ENC[AES256_GCM,data:Ll3OvOF7/r3Kg8t5,iv:nHMyum+qo90TTyjUJEc5YomcZN7kjdJMVJ1oSLds3x0=,tag:5nu14U8GypPJUKSo4DpObw==,type:str]
type: ENC[AES256_GCM,data:cBzawRUB,iv:HCtuDj1AV6J4v7KGDWQY1LrGInsD9lMX98eJG03Ux8k=,tag:+ra7Wg4xniNLh5N9Zt/1SA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:YFTI+T6zohQ77ouVMcnEi9mLLSX0xqjd6K5gSkA/iL0Rps04Xr3BQcokmpp0Prk7/15piQo=,iv:1QRXOKkn9AEVMsN+EsVDp+eIm4KcVgyBjepBw6ySfAs=,tag:VzMb6ke0ex6oNJ8wNzoNjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSzNQbndOTFl1bmZNUnp3
            dXlBUys5Y0UzVFFHSWZRNXFicVFuWmtKbG5rCm80VmxYb1lTZTR6Zmp3bU56Q05E
            N2ZyMG05Uk1xd0k3TXhVMkRYYkdIbTgKLS0tIEc3ZmxaVEtSaVR0aitka0NQRjY3
            Q1lCUlpuQXJ6YmMweXZRaFF2Y1BKdG8KlPe3LFiSbTQW4Kwk10PXuWjDJsVNPTKB
            njM8mzOMN8xKdSOu8BHOVxJ11M/RV3j8OYh4ACkvWHqMCmlrykPPrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N3UrNVBSSExaREljSTlQ
            REltdDdFc1d5MzZ2MmlLbnpmVnRWQ1VUTkY4CmJZUGxvRkExa2FNZDN6TU02Szln
            U2dVQUMzMStzMnpiYVRhZEozdmpNVjAKLS0tIGZSQlF1M20yaEx1TkdCT09Kdm9H
            dGt0a1NiNyszZ0FuZ3gxSlhRb0NTWlUKcH4wBGPtHKJfWro773WDUZ/6dMSUvURg
            BefiSoFar/sUO/kxjSyIXVLfARFsk9eFTtDAJIvHZVFmBIbPLjFdFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbUV1NTQwd2NHclI4U2Zy
            ajgvTjZxMXBqYjhZdXQ0TkFhWWVuUmI5R3owCnZwU0I3anlvUlNQUnNlSUpMeE9q
            WUhwbDJWanNpdis0dzVyQ01XZUVLV0UKLS0tIFRnNnMzY2w2TXlIandrRS9iSzlL
            U09kTDNyNVgvQ3o3NmpwemxQOEV1ejgKFuo6tURb1/DHgWooHDAY8KOXNMdCxYp8
            ZXj8PA3agyopqvk93ZOXA9dPjMrBbbkKnxr8xJhA+P6wdVz5ah01Ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MGpseTNmdWt1U1FuSDJ3
            MHg1eHZLcHIwb3Z2dmhITTBEcE8wKzJnZ0Z3CnhFTldlZC9QdjZhTGhRbHVWZEdv
            d0lESXh6VG1pbWo0V252UGVNa2dSdTQKLS0tIGRJbVNGdXcrQU1rM25xVVlnUXp0
            SlNVVEg5SldKRytmWkErVkNTRTEvbncKRemTCyfYqTVLGCxoV4V9pkc7kjwOKLfC
            7DtmiGQpnU2yILEEg2+WiadsIVuQx+7aq5/LxH/vsKdeDiM/MVk81g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T00:23:29Z"
    mac: ENC[AES256_GCM,data:z42ePrqt5ei+t0zrHdjHQ0D9IKZ+r7sUb2sB1AbmEZosfAf/Kc3UqBDkSkv9SfIBmc8bKixJsJjCSaezuQcBXEXz0U3iTC2NlC2WFo5g/1c3uBd95p6N2T+r4/F80WuhRyjW6osKo8Df1P4qV71X1/HVfmgAioTG/pPTxe+uDcs=,iv:IksikZ87Ev/EMGiHcPplLYpTfyObXAUXOGfwKu6+UEI=,tag:cxXgJfkMBSwkV0m6vHNCKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
