apiVersion: ENC[AES256_GCM,data:Fpw=,iv:5fj9brunMvcMfXEplIK18bQqKpKgDGva26mxKyZCp70=,tag:jQC2qi8UNy1UVfo8AmkbUA==,type:str]
kind: ENC[AES256_GCM,data:Fh7f2j3l,iv:o4ocD6htKxad8460SD5ZIXqTtgrJ+o7V/yJ5MapYxiw=,tag:rNf5BjUkGtxMF1jpNF3d9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hC9W+OYNydKVvDky7RQ9Yb1iS1YA6Q==,iv:N1ylx61HS5j48kMijYRIGgVNByBv6TFZVm25qzwugqo=,tag:Y1oXKf5KLLiXBk/gNHmi7Q==,type:str]
    namespace: ENC[AES256_GCM,data:AWp5EH2UFWJyEA==,iv:T4y5F4dCrqBMqVcm2ZgFl3E+UDJJWbN8Qfbz8yzHf/4=,tag:ijk21GAJLbH4VvdsCWbD8w==,type:str]
type: ENC[AES256_GCM,data:Jn2PYGhu,iv:+PtY4XcT/0tS6VZEmuAJ4Fg1HiPzL8iWVWsVpTd9dTM=,tag:d0amvFUQ4ZwHbRE7fU43aQ==,type:str]
stringData:
    discord_webhook_url: ENC[AES256_GCM,data:hJZwXG6l0E1bREYn00n6me53bCk3MGxu3D3joo2HLKhZQwplQaP3tMWZExc8aEL+KF7gCC9zPy+IHIZx3bpdXAzkZWg+VZLgK6MwRungJjd+8HzymDCY6ItET/trl20Kgb368slAsb4r3lFU,iv:6e/NT45R/OiGHL4ty/kC6z2exLfis9Rm1LEpv7nUUEY=,tag:ZBmcR6Z60yTPuFV5k+Qg6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ0VTNGU1TjhzY0ZZb3RK
            R05kdkp2YjNyZkVqM1IyUTJTQjd2a0Vuc1NrCldGNmY0eHRCaVFYQ3ZMN2hqTy83
            VzJ6T1Z5dVBJWU5DRUttRDBkaStRVFUKLS0tIC9ZbzlGZEQxYTR6R3F6LzBldC8r
            dXZTZ0w1YjJueDR0d1JHWHB4clgyVVkKVgucH6va5JaXGjtiBBw4B23Dkc4gHEca
            zyEt+jHWhjFS9y7dMXRBCzzsvI+KctLYHZ6MWrc5OBz6xwh0+RyqJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ3kxK3NxZVgzaHlkRmVi
            MjhWM202bGNZdjBZZkhvRzdqOE1RclJSN2tFCkgwQUdieVhCUW5UUGpvMlBuNEZ2
            ZkJleEFTSEtMc2pFR2ExTG9TS2dzam8KLS0tIEoxUDFEY2RGVWlNamtweFd4ZVFD
            YTJJZG5SRHFoZEVWRk5kSkVtNFBEZkkK02WYg3HZioMCYx/IgZ6NDzScXde++x3X
            oXIzkIJNrFa7b6i0tccIkMyb/8s24F9sB3f98AkQu+2hXrW9702c/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M1NVdVR0NS9TTTRGQXZF
            aHcrS0U4VlM5MkliQnFndmtVS3JVdTJNNVN3ClZxR3RGeW1UeFV1eWNNR08rTDZi
            b2J3ZE5BTnQ4RDkvRWNtUFJwMnJsUkUKLS0tIHZ1YWJOSHdqQWNqNDVoeTZIamdY
            b0k5amhqb1JKYWlwWnNmNnczK2IrdnMKpK8/WviV+TN1l815OOZzNdzplY6mQ0vq
            XyARV3c3Jy7mjU+xnZJyLsE+2yRD7YmUhXpiq8F1Ekh04Ux6srnmjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K0NrdWNuNjh2S3BTaVp2
            MnJYUzFPRGxiRzhSYlJ6d1ZjK2VVUjVVM1NJCkEzdEFmMEpraEtGUFEvbmVNRUFo
            VlpkbEtsZ0w4aHdoSW0xZVBhWTNHR2MKLS0tIDRENEhySTNWdkhSa2tDdWRuZk9M
            WXczaURUbDNiVHpnZjFpTWR6Vm1TaE0KSGmM7tnKnwDhPyhYzcWZFNFpGxumWbgP
            yxzmvp68H74/0AKVPXhM+AviYtzZ1a/jAC6OHB1kwHiAs7bXDPPlSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T08:58:41Z"
    mac: ENC[AES256_GCM,data:hpRXqqFPzc5E5AsEQJquk1RWaIk/lvF9kIFNssZOEmaFBYmg6Ehf85QY/oow+sFQm0hXCC/ciZGG/AwcMIQVfk+DCEpraHXsDTbe7Kd2LtR+BsEulQNvMIJBc3qp8hamRY/30cQNUB6XkgDe7urf5HPofML7Ooe82rpPdAhwMPs=,iv:dAdaa9i6so9NS6prZFXJLS3RAcamFzhI46VVgTn4P60=,tag:Zdo6DbTXf7ulMxvsWRaKjw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
