apiVersion: ENC[AES256_GCM,data:SZ0=,iv:dDOVgWRr27NYboq0aUHh8xijqw7XY38Dn+FjTEOcbqw=,tag:uaVUom/dmUYTjTBJO7AfPw==,type:str]
kind: ENC[AES256_GCM,data:+ZBK4fRi,iv:48PIu69RNmnL/lvlOmuJI7ETcG1oQ0QuNkBhKwf4nRg=,tag:bLBEJD+S+JmqVGwkNdxiiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RsttkUwb8sHgMZLXPj+qyJW+/nkpYw==,iv:UWNBEpoaEPNTslqksPSlaN11fBIt9x8R2K5uucpiSEA=,tag:5idPgVbH6+zvI+TMumzCcA==,type:str]
    namespace: ENC[AES256_GCM,data:5pGiMtntAqgkhA==,iv:xNUEjyctkrQH/IWVETsfxBjNCJhlbOszCh9fNOsK2Wo=,tag:siT/gDba7AiUc7xYw00AIw==,type:str]
type: ENC[AES256_GCM,data:/6sKKS3L,iv:03wHopHC85PAjDAOWH2EmycnvAV5kOAKp0uRbKK1O8w=,tag:tIkvwVqLfsPnwtoa34+h4w==,type:str]
stringData:
    discord_webhook_url: ENC[AES256_GCM,data:6ssX3lEdicPy2Tr6gbnCxULQDNR9+qRnowDkpyazIW/ho71kP9CxWOrLt3EpDpXFMBcnxKPx0aSFiaYwC4Z7B+Mzq5GK9XupG5s1fbyFIZJgIlF1UgSjvUWDfpoJHSK9G9g=,iv:mjJvSRFsQqYkK3kZkmIoibbXcQH9bl/5lwDmmJmSE7E=,tag:FbAyVTWLOTFbODEvlSPlWQ==,type:str]
sops:
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdVZLUnF3NHZLbVM2RFdV
            dStrNitEa3RLVFovc2pueDFJd3pOVnBMcm1nClNkMlUzS3pJWXIra3o4eHBCazNE
            aWpxZmZVUGVHa09YZjVWeXpsdHRVcTAKLS0tIHNEbTNZV1V0SXB3ZkFBVDZlU2pC
            RmZZK0JOYWkxUXp4dHliTGdQK3BxajAKpTs3Cw0iGfG7GIh7IZeAE6pqFGr8AC72
            ZqhLDO034tQdxL74oCJQmBof+v6g+Me+5CB9Q0PkR5XZMsn0CiuNEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT1oyRXpscVJHY3FZcGsx
            SnUvSFUxaGx4Y0VoSFkzY3NYclpoczJBMmhVClZxRFVZREh0b09mM2lwYUkrNmpM
            YXdZc1MycTlWY2l2YzRlWWZPRXZ0VzQKLS0tIGNFTWJIT20xUXF2d1MyTFVacDd5
            aVI1SHFKVUZKaG0raHlmeXFBWmJ3aGMKLNlx/mWmt3iLt3PD8kGSHvMjDLEuRzAq
            er4K6/qFoUWaoMRPIbBQotB8orUSA2BpRl5Q+p4mEsv/s30/P5eZog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQWRnbG0vR0Uwd0NjaS8v
            V0s0UmNsU1pzcS8rODMrWVJCeDFMRXVLNVc0CmJIUGZUc1Zxd01YUFhFNUN2cEVm
            ZWo1ZjN3TnRSd3luRzdRUC9ZSFMrYjQKLS0tIHpwcFIyVkc5eWxZZnlQRXRjUmpF
            bjFMK3o2UTJMdHlzRTNUZndOdmZOWFUK+2QPABoZBLv0JnMyFGPnTNjGDwbt5w3e
            L1WYyMqTrl/uXYS+9RFUqzX1PAQs0JWSGWHgrsIGcOhlkbRkFTsJAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSVBHOERlaUVLM1pHUEQ2
            VnZ3YmQzS2N6bTU0QjQ5SjZMNUw4OCs2S1JVCnlYUmJMOG10UkxSQTJtNmgwMWJC
            eVRDY25rVXdYNndDN0JxQ0hEOTdiak0KLS0tIHEyZTNURVlpUnlWRHNsOTZ1bTZI
            dE1kTlUwRHM2dzF3eXNRYTIvS2lLTm8K3XyOY/SuU3UKI+192upX6rTjE5F4GXMr
            25KrBN7wI2iXZO5BCAZz9wAHHggttBBg0NIyX888YukIXsxg3RFCqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T15:32:18Z"
    mac: ENC[AES256_GCM,data:wJO8UCxbI6IxmziWQcKUNOsKaTcHbEm0YqwiUtLs6Z7Uiy46vuvv2BUeKpku0XLqwBKxFItInXlBz4dPzu4gcwuuNS0eytju3ucntw84HSugfbs0BBuSYvYOQXYtm1QEzAGJzOsNSMndvE+FWx2a1U6O5GGZhp90C9WjK03t4fc=,iv:NosY3/A1Hf+VBWg+9dVg+I4z3Lo/KZQM8gUKMo8L2D4=,tag:FeJU3VUxm/w3llMQyH7FNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
