apiVersion: ENC[AES256_GCM,data:QHg=,iv:PxkESlYQisZTUZfHtpUTinfM28YUBDFvuI51JC1kqHY=,tag:R56Zpi2QrdxHI9yyX6T7WA==,type:str]
kind: ENC[AES256_GCM,data:Jiz5oMzR,iv:204nX6u05jiyBO+VC5GgjWivnIIqMKgiS0EkU4SuwyY=,tag:LUDgKl4GfK4Tk1BZgNorxg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kqAdmcADJ+jH6MVseAwd02Y=,iv:X3gYUYRSdy7F/KQvBab93jopuON4f5rgKIBcH4mkFLQ=,tag:Zcj+A0tVaILr63SX2JGyKQ==,type:str]
    namespace: ENC[AES256_GCM,data:vRcw881RttNblwg=,iv:9eNFwC+CMsRObTIkC+BDsexqTMxhfRtlZo0dW9zPRqA=,tag:4J2rx9j6Zwd6NsrJN5bwmA==,type:str]
type: ENC[AES256_GCM,data:55e7Qw24,iv:yo8K/MKT1dFd+Iy32VeqMdv6fgtnLdTRNWLPhVBWOFs=,tag:/AUQvjSxEIH9+IuzMnzMTQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:7QgH1Xrx+9TlPhDnu453/2JFwZpIq1g3AMgIXXokDTL62sUMyo7WZDWuXiAl0JDX4TC6u7rTN5iHkXmFcbaC6SuoXS2wFHArVNcQmxCySRHik/0JvLhUYrseTF3APr8MrNwMRMbD9rlbg7R7/wDbWsOg6WJpxjL8VzTQ/tJ4DYgy+uEFOGEFx7wo6JTua5Keq9abBieo4w3cP4YmddkLQK3K77/CCCQ3Cthjfk/NmKO7GbJa1HEK0g==,iv:4uNB7Q1KgyDJ7a1SsdyiRZVGhrcumw8I0RV8xLyECjI=,tag:pEPzS397Vupjc+1EmLqeJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQUM0VzFNS3Btb1ZFeHk4
            TUQvdmU1SWJzRnZtZWJvcFhFS1BzcVE1R1ZVCkVzRTRMRjFaMmRMbGw5cUhlVHE4
            S0N2TXBOd0NyaXJpOXR3MUJoUCsxSXcKLS0tIDhoTFF0Qm0xQVV4eVlSY3lLTi9n
            VUx5NTFEM1pvcmI5M2MzelBJdlh1KzQKIbr+czByL8v6JsN0N0KmWpJguoyw4nM0
            QWr547eGObDejFICZDvVURu9KGFJp/U+ZPnOd/b72/s4d/qlgBPytQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbnkzbjFZQVI0UjlSZ09a
            UXN5clNzL05qMnBRMWtQZG5KU3NvcjY4TXk0CnhZUjE0MndkQTd2Y3JPeDFsdHMr
            cVhVU1JlTjlieVplSmdqTnJGTWxhTFUKLS0tIEtjMk56b2NsUC8yU21sVWsxd045
            bWhYUHJENy9BaTUrV1Z1TTZXMlFwQWsKYYQk756QPUTcfPzjDVy8ap1GVpj0HY/x
            nUlryrRgWev0LzZoiNnDYsePC0BwCz6olcWnZsdP7oZGSPdzo75vzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWEFmTjJtd0JsYXFQeHVD
            NCt5K2ZSTFVjMDduYnBBTGMwd242WDVUcEY4CjBTbm8vVkVCNmUxQVduRllDQVFZ
            cUZmY1dtbkdXZmZBNk9GY3VhYUJrSnMKLS0tIDU2U1BHTEU1OS9pK2J4T0dhUlli
            dHA0UmRYSzJtdW5PNUtZb2xFYVpGQzgKLgFNp9bZg2f+7LecSFMG5Cnx4pi1j1oB
            LUpuEAdEVu8eJXRwlBxJFQK/voBpU6NY2SLvbP1bkl+7w2mFVQ3IAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRGNpb1NlUGxrR2lpU3NY
            Sk5HYWh4QUVXTzlVc3BidDRQUHVPeFhkdWhVClNLWXFKT1QwbGJuWEJzU0RKWWNv
            aCtkb0o4MEphWWYvTllHVEVVdnhFOHcKLS0tICs1ak9YZktvSEtkYWltM2ZwL01u
            M1RUYVY1UWF4dkhJLzhGUTFhVEQrd3MKl7wC1UQeukTvSZ+qhOD1m2TIF4eKBE1p
            zCD1A7dxs305mcGOJp6PStFaoyqrwEjaGq90tWH19HWg7MsDOYtMtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T07:18:47Z"
    mac: ENC[AES256_GCM,data:LUrXwfnIyKHSCbN9voaXQjcPN+kuWRxR5BBiuGMgaC6hKayMAvUQHV1IvrBpauvgMWwJUSjiLQbALI2MhRqpPQOWeISsvPNkezEJGvEI3Nb9d99C7I8v3qJFwL3Ca55lQZaK769Na3MQYLSh8aTsAdNExJygtktJ5Xfs94HjldU=,iv:JZAXgFgpxIn1jf6IuHNzYF6STyzZ3p5OeiqV+mCYdIM=,tag:9x6gbvsCXsbXWia7wQFJKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
