apiVersion: ENC[AES256_GCM,data:pPY=,iv:M5JOL8nIeloubAhFgFacCVDh3byWtThaWIgy+XJrvYg=,tag:/VTiuhFlvToW7YspXsDwhA==,type:str]
kind: ENC[AES256_GCM,data:v/zRkeNJ,iv:Ec4ble9ED99BwVHE8XzkzBOxfKVwbi2+bf6EvdAbQJ8=,tag:WW7rNxMcFo8ykiYo7phdvg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+OPOrTVBGSRcZRfR,iv:BqRVAG0ZvDEL9u7z5/ZmE0vfxF+V2W39nyFblng8Huo=,tag:kKT0qxxhroSfSzx3FiRxJA==,type:str]
    namespace: ENC[AES256_GCM,data:Wkvdvg==,iv:W7TwwLTl77X7mD0WQUmjz2R28+j0dhJm68q29wHA2/s=,tag:Bx3aMqmJKxGH11xwvx6DoQ==,type:str]
type: ENC[AES256_GCM,data:SWRF85rT,iv:hmxbzJerVywUl5ZFMoYFuKAAY0ENh6VGcNV8Rqyphok=,tag:sPAevKRDWrg53vFowKyJJQ==,type:str]
stringData:
    dbPassword: ENC[AES256_GCM,data:SShEaCcQZ2pps/81Dq5OlAVda6Y4epEbha6/9WYcq6o=,iv:j42emBOl1CZ4QxPbHMrItC0ykbGbLkZSA0/8jg5CjKA=,tag:V2bKDsWW+U0hSEhEptyn+A==,type:str]
    secretKey: ENC[AES256_GCM,data:nXjBanfzCZY+42/JXRJ677np7O4n9P36VBRSQAQhggWx9E0jDOYW8lolCG5dr1iRiKLHwpSpf7pd1GR8LZ9a7Q==,iv:WhzzifJ8DPg1huNNOzWyq1EdfT3v282HpiPDNLjWpHc=,tag:MJniMU80xogyOO63kYtrUA==,type:str]
    igdbClientId: ENC[AES256_GCM,data:MJkJ8yaS9zr+4LhFFqUVFC5HI2qUkuFgNeIK9XOF,iv:CXCXcobnqkXgm8+3vEdWShlwrNsZ5mXcLH+Zu672D6E=,tag:AYe3KydTjHyw67Vg5Q1jWg==,type:str]
    igdbClientSecret: ENC[AES256_GCM,data:L9F49hYxjckKfouTB18ReqWDOILmoUFFhAMNQGfn,iv:hgBtq/3jIzK6aX2Jn9o/r9FWO/oq70y6uxlnESF8TWU=,tag:XCV7eF9lEI/0HWEOvhnSxg==,type:str]
sops:
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Y0NDdVFvQ2xlbWpxTTI0
            RlpobEcyWUp4UURvNndKUTMwcWkveHNCK1dNCnNjeVFFS2hZSkpVR05ZWjFyV2NJ
            R2V2ZVdJbjJmbGZ2emZQYlg2NWZqYVUKLS0tIDdnbFhCQ0s1ZCtablh4eXp6QUwy
            K3pFR0FOaERuNEpncmZxL3ZZbzdqemcKnbvedu7pB2sGBIki+lZU5g+ZNCJV24g1
            wsYFp4+4tLXCMzvIwXvqvmZB8eFWE2rH8FGgEG55zMIpaMgFIFdmZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRVRnbDZjcXV5eXczejIr
            aVBEWklqZkpYdUEwU3pPaVJyZGtvNm9icDJnCmwrRGNEZ2NkZ0V4S2w3RG12bmJt
            QlRGNmtRNW5ha2RPL2JXeHBpN0UycTgKLS0tIDl4bVJqUmVDSTA0dFNYcUUyRVBs
            VUl1a0t3MFJKL0JwOGdTNjU0M2NuRXMKa+ajfh38QkdFlZqtdtErb6NBhUMXcuWH
            1K4yvxTkDqsJVvA5Zq3irgFc4efSaNj0N4dvnygnZnUKdkafMQThAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRXdtOW40T0RiZEtadWph
            S21vSkcrYmxNM2FCdCtZZU5neUxVUkt2eUUwClpteFlkdlJCeXVMaFIzbllBRm13
            azJvR1diM2hKWmlybG5WNy9PTDNadDQKLS0tIEpYWFRtNTZTd2kxYkRhMnkzakhZ
            NllhU3VpR0JkSVpVMWUyOENLUTh3dDAKOJHYlyVexJMX5OzF/e3Fgkiv4Cl5t86i
            75Ij3jR3oDsUU+PW4eP9YbgCIFiABZHxrIoXf2PfdNh6fMfGUyl5oA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRm5TV24rbWhaUW0wWWt6
            TWZYcHhvWjB2M1hsSzRBS1FQMm4xWVozQlJVCmR6dmFPRFN5S1U2cWViRUxDaUNa
            NkROeUt5WkRHNXg5TitSdjQ4UEcrdWsKLS0tIENqNmpyYVlmR1M5QkhQSW9yUWRz
            M0ZYVnV1THZYeGFiam11Zk4vbHhJU3MKO8TsEO4tRn9Prug8IW9Yt2pSQEvm2w7w
            6AIUsaDkuNVV8IGlA7/vJpkwbObo3aBw9aAmkeBywju++oUL4f1kXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T21:48:37Z"
    mac: ENC[AES256_GCM,data:tmgqGLKQTKDEd0nxYGNAXoOin8FZzDC6nNtQmv74fA9A9478YkCO6x2AZvxUCVfuhqrvKQ+rjOGUChR1X3sOyfxLUBknHvwl6N52hI/eZZb1oBZWDIQgGqGDm56I6NCiBPoP2PIqBrPgEXEwWddB7Ro69bZTcWJQonVqjkjthac=,iv:kAkRNoWbt7G4DPAJ2xTrKwXD1cDScipC/muEq+nr+uI=,tag:S0piQolFbOxvUHKG/JE7xQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
