apiVersion: ENC[AES256_GCM,data:/5Y=,iv:SgRwZM9DJuqzGMasvLq6+e4VbE7dKoPf15Y/AFDasWo=,tag:PWYCAdgt9VSRwZBWezm3ig==,type:str]
kind: ENC[AES256_GCM,data:9lAEFRCh,iv:nmoDoNqmlxL8g1ND2RDYG890ShFYDc5ILaCxQD2x+ms=,tag:i8OwO9X81GCjdO6oXOZw4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZcR7bCsc27FAGwWi,iv:O4KkGu8UR3x7HSaDgYg/92fAH+c9LQFTkSrA85gYOCA=,tag:LkTIcu4amaNG4pYeMHMqSw==,type:str]
    namespace: ENC[AES256_GCM,data:OMw4pw==,iv:a1DCG4GFc7ZRNTS7Scjes7V1TJDGzCGZ8Tv1vPij7y8=,tag:5mvWfoo0Cty/5ByNG0P3fA==,type:str]
type: ENC[AES256_GCM,data:7RuB4Lx5,iv:4kCo980+IV4fi/xJLINz8yBjqOoygswTpO7ovkFZSGw=,tag:jfU5RpXl37dUAMoAGXDuew==,type:str]
stringData:
    dbPassword: ENC[AES256_GCM,data:WeTK4tdg0ukApGf3beZKmjduoHMJS25y7AJmdB+NPBM=,iv:Za2b5UVYCrwx3N/EzTLxwyJ/96sXDHS7hBp87UkD5hw=,tag:GbJqyh4nC5zvwFDrduCsPA==,type:str]
    secretKey: ENC[AES256_GCM,data:quh5AQzEcNUDPpjde3HxHvCCqzx71uw7qEFaqAmIZ+/bXIcnfSYhIlzF88PqEaL3T9dF+pPSnMglzWt8hkRjOA==,iv:EdPgO5DGAFh7murZZ4pbWquaXQZkKf+kfkuZW/T5i4Q=,tag:IRfnxmFw+WUj+6np2vFh1w==,type:str]
    igdbClientId: ENC[AES256_GCM,data:eKKQ7RxxJy2b40kTpDyx4H1a/tr2nQIw3gUNPkRp,iv:EG6Lli6DETSz5WZ/A0SeyNZ8eyA2zYxlhS9KwjB0xKQ=,tag:Su1MTCJhG6Q6VMfQf7fZ1A==,type:str]
    igdbClientSecret: ENC[AES256_GCM,data:Prq4gmepcZwYWW3/yZwUY0q2wYDHn/Zwh/7Hg91x,iv:/V9yl5OH22ga5y+Cb1LWX0roGHrCnCerjlxJGERJcjE=,tag:HcTyITSbRvuTbK6XJScl6Q==,type:str]
    screenschraperUser: ENC[AES256_GCM,data:Ey+GEpMp0zHIvQ==,iv:P1fcfnIQo7lf/Z2JHw7xhCv3Aoo6LUSJCFd4pPhZcNg=,tag:OChdrmm8ExBtsZHMIbuhkw==,type:str]
    screenschraperPassword: ENC[AES256_GCM,data:ck6EtU757SujVP+bu7UZ,iv:JZkqLcakAOevmNOa6/iO1pZcgS9+2tEOjjoj1GbCXvg=,tag:UKHuNYX6FAB4sf/4zZlNAw==,type:str]
    retroachievementsApiKey: ENC[AES256_GCM,data:xU9t7X0rhoesQZ7DEtX1CYwbwpmXZnNQPynOBY+HmvQ=,iv:kEIhfl0FIH9fzJsczCjXTNniDRARUyJhFwgU2ozQcsY=,tag:p+p6HXicA0EktrOVT+L/2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa2dQZ0c4Q2tLd0pxM3Bi
            bDh4OHJQcGhZbFRHU0U4aVp3ZTlhWGZuNFNJCjQ1YzVVTEdjaTBXY3pnNHRndXFo
            TXd4SEIvQTdBWGVEbFpzMkNBREVlVjAKLS0tIDd1dTRvbUJ5Rk9ubXh5UTdSNEdI
            Y0w4WDY2YmZRb0JXS2tBbFF0ZGJHdkEKBNvNTl2SMsdXGSvYGK1C0ltt8xHR+2OU
            XCh+hbDP/CczJTOr/1Qet3H8y7z2dDHWHvcvfj4Gn3kYArHtwtOUmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOTZlNS8wOVBFQmVRS2ZH
            cG5WM0crZkFoL3AycENsektKS0wySHhPZ3pRCnhhNThMeDNwQStxODg0VnhmNTFE
            SlJ6WHozQ0FZcFR1eVkzQzZLdWN6akkKLS0tIG5RYyt3MVcrZkFIUUdndDdwVXhC
            aXhPaEVoUTRkcC9XUUMrMTVDZCtkWXcKjnvaUOcWSbT5lSOXDa39QaK/HlEpcdLj
            0HM7Qz+zLN03TatW7Fx3ELbJNcnBy0ocwU79PiHwuLxamK+Z1E7J7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U1k0NVZwVzdnN2hsRm02
            eWwzcFNiSndXTkFKV3FTbFp0RjhIYXFkOEJzCkpYZU5xanJKemU4aFRhZzNuWlMr
            WTJ4SE80THk3dU9OaG5sRForb0JSSm8KLS0tIElGbFhpWGNvbXI1TmxNUEtYNmZQ
            RjB5NFdFcWJrR2JqQ2xaS3FmS29DVUEKpfw1iR0OzwsB0yVMjlD/oQ7eY70w1vNN
            unyPrMn9MNxFo1Y4GyIWMR5jF+UItBuviqYmdTQBy6Gr5nRwcqGkGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbDluNTJmNldrL2dLcU1T
            L2xJaTF2bkRUOG5WRTdMQ3NqVi9VWHVtY1Y4CkQ3c2phVUV4czdRYWpTeG84UXZx
            b1VzV1dLVGVYemMxUXdPNWpDSHl2RkEKLS0tIGdDL1FvY0lBd0tMemxMb1FUTFp2
            VTkzU2lBN0tja3UxL1VPRWU1ZVZHN00Kl9Sd/mDwMJ8Wpnc7Vc0Q8DIoGFTF/pN8
            LttqyiHxpy2SUYQ/TIIsvB6fwY0UWPvMXzKUYUvnSHG76NSM/VGMPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T12:05:30Z"
    mac: ENC[AES256_GCM,data:TwMXTN2HzKkZXFs5AF6W/e8DOEAw55acvzVmZ9/Wh4xm1HqaNfQhzZvhtUMXvQ92KsYiYWskAnGL2NWAVvTHtqj7/ytJ/Yd725DhIQ4Alo6BwSuC3l7Pox6Us4dVPMd5TxBkBtMORlEosHIG1GfDNiLXiFlyK4GcrXSMKNglPSQ=,iv:D9X1HLiQ6FXfyXXusrLyq1wS4OmMPpZbG7+xkjM7abA=,tag:PnDouIxk0OIl8U4PY6MLZw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
