apiVersion: ENC[AES256_GCM,data:YPE=,iv:cJtxwQy9w5jgoOyg8LEWTXgubWO+vm5cBu2kaSdO594=,tag:tWhQMc2z45zOFYww+E/lPw==,type:str]
kind: ENC[AES256_GCM,data:RPyNZ/yq,iv:DOfaNS/nMZmkLQIrGWlqPrX1ee0nY2v7vCT8St6kK/I=,tag:sTRrMhHipaR9+7BWMjcjIQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2pF6EKfTa5aa4cHe98Cs,iv:i1WVq2Iy/9YdNRSCAcE+8DsMol20ok1CFPbCAPlmZEU=,tag:/tZMDjn3paXHdDqNhKhc8g==,type:str]
    namespace: ENC[AES256_GCM,data:D9dvGGEJKdU=,iv:HxxaUvieVFiEFnFNIyGAvMcpyKf+7NF/3ycQN/02b2A=,tag:2+KkRy4QQbY/BS7V1O2yHw==,type:str]
type: ENC[AES256_GCM,data:yh5+2S5g,iv:iQq0+taU3aRLA3jdgkxJs8r8AGGoJNbI0MWUIvHT5Iw=,tag:W2KeSWdur+s65DJ7+MrX5w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:TKCqW4U=,iv:77lyr2VVH5tFzyD16w1DCTFuyC5KS9M8bNDexYMPfIw=,tag:/W0131CkVmwk5oKwQtGpXA==,type:str]
    password: ENC[AES256_GCM,data:wFzHATSJXgdd9IcfQVo6QXl7Co1BgTFM,iv:qY0y8WwLh/BcmylEivY1eR+EiTnq5K60YJef6ctRs3E=,tag:Z6Zm7Lxh/H0LAaA7Q9uyGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVYXhhbTBHNjh2VTB6SlAr
            TFRKQ0xYT2x1K09DWHhMRmlObUFtd0lFZlhNCmpSY2dDSzBsb2tvODRhMEh2cEhp
            bnowSEl5M0tNRzV6N2lSL0pWblBRdzAKLS0tIG5TZGovVmczb3lGKzlhekpuc2xK
            cHBvUHVkMm1XQmlQZHJRVWUreDRJLzgKmxBohvEkmPAuX392tM3Ni8yueGpwURoG
            dhKZN1b066xW3EaAyItze56DZCEVDmcoLMETOBxKp7HD5rtl9D6zYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UWp5aFZhTWdIaG9LY0pG
            RktzcW5yRDZqbU1sMjNJVW9rd2pNeGdjbXprCjVBbUE3aHFLS0IwcXRUaE5yeExS
            d1RnUi9Vbzh3MTJuK25NZjZMay9rNGsKLS0tIGlaZVNTYk9uNXBNUHU4TndpVGJF
            N1FMSGxuSHlhZDBsb1lPVm9IMUR0SmsKWS7iLlzCsRw4OehWg2Um1RCGRuRLEYqc
            GQ86DzGbiCvmVYxJJ//rIpwZHYjcIGdwaiadk6puaIoMtrk0WQ8flQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNkcxc0dUektpaGRqZzUr
            ZWJpOGV1YlZJUmhVbGtINlN4UmdwaG80WVM4CkVHQzZCS2orQ2cwWlhDMkhNT1ZV
            V2tveVNIQmYrN2NvTFZIbVh6NXZiTDgKLS0tIDRrbjFlOTB4N0k2V2JKelNQck9Z
            WUpqeDcyUmtDeFdHbGNUSHVGU3d6KzQK5lWG7tgFvQ8X54Il1mMPWqyiYmZmyFzc
            6IuLPTelrf+8B3RD7YYmydI3qIme+wbsyYeRNzj+61Oyd3d77rlwDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTXE5NVFBdVpwYzA1ZWc4
            MlpaZkJCcGZSYnB2d3JkMitSeVhxTGxhQjJZClhwQ3p2YTJ0M2Rrb3RpdG9HZ0sz
            QTd0akZ6Z2RtY1VwNWlOY3pJTFRjR00KLS0tIC82azJFU2ozeEdyT25DYU4vbE5o
            Q1UvaVhneFRvWXBMekhHOGFjcTBiY1kKvXCS8k91ndq9Ug8hnJFNLOP1gepCWDKq
            /FrKyV23S9m4P0A7l84S/xHk8LUL6JRBRrXgolqx8monBwMchoYDFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T13:22:41Z"
    mac: ENC[AES256_GCM,data:t8I9z+g6GBx19a4TkKGJiqG94i/DaDtzaKXAppWbyEN9cc26D7R3+MS/+5qRApMjstsFrJcU327wtn2LS117V4Vh+Kc8WW/NOIuypcD3XJBePauG8WX6N0RhAkz+xicQI4ayWIxFjON8dhSJ6nCVSgIqXlcARvH+DRe+6qysa/s=,iv:R/CnXcW5VwlS8L/JPzlLs2oRP+PfKfP6NU1zb+S2hU8=,tag:sPYWNK9wbrlo65bquCuOPQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
