# ---------------------------------------------------------------------------
# sops configuration — age encryption
#
# Workstation key is active.
# Node keys worden toegevoegd NA eerste node-deploy (Fase 4):
#   ssh root@10.0.20.1X 'nix-shell -p ssh-to-age --run "ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub"'
# Dan: sops updatekeys secrets/secrets.yaml
# ---------------------------------------------------------------------------

keys:
  - &workstation age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
  - &node1 age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
  - &node2 age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
  - &node3 age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y

creation_rules:
  - path_regex: secrets[/\\].*\.yaml$
    key_groups:
      - age:
          - *workstation
          - *node1
          - *node2
          - *node3

  - path_regex: apps[/\\].*[/\\]manifests[/\\]secret\.yaml$
    key_groups:
      - age:
          - *workstation
          - *node1
          - *node2
          - *node3
