---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shelf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yasuke2000/Homelab.git
    targetRevision: master
    path: apps/shelf/manifests
    plugin:
      name: sops
  destination:
    server: https://kubernetes.default.svc
    namespace: shelf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
