apiVersion: ENC[AES256_GCM,data:7WU=,iv:0lb+YsqXA7m5JffKliHY9fY8h693/ThQAPP1XcNe57Y=,tag:brROCE0ofzEPXna3GGa9Vg==,type:str]
kind: ENC[AES256_GCM,data:060Hq6cN,iv:0xjjt1zZye5+nSrkvPL8VF0Zis+cqlZ0OgoWCG6aBIQ=,tag:KHFE7iAKnIMcgJo1O7JOkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CvPPcgUs3ys4e6zi0liYYkXT3KY=,iv:sSPf8OIzsgxZlgN310166fURK25OT/s5guFWp3QpB+k=,tag:rLX3R5l31OoUA7pnsWc5zQ==,type:str]
    namespace: ENC[AES256_GCM,data:AJbiw/F95EmDag==,iv:H6274RyDKkWaGdZpJDzEWzxmhduXBaH+pmIsYeGSQ6Q=,tag:LjzmhgU47feujq9C0Y6JDA==,type:str]
type: ENC[AES256_GCM,data:97eZwwQ/,iv:5fOCHMvN8bLwjLsrUjVsrJS1dJjD107rIgm4BynzNaE=,tag:CoyR4BYNeheIdN0noX0laQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:LJzr/ZE=,iv:roQHC9BqcJc9A65w/OKPMhrshzhJpUG/GqBr+jdMdEc=,tag:t8MOTdhTF2qcOVgmn/UoqA==,type:str]
    admin-password: ENC[AES256_GCM,data:68KonRSiA3wUikYv1Ue4vpkhMb4L0sE+,iv:g5CKpuAotnXYLwDtYLw4ye3MdfrkUaRzN5SL6d0VG7A=,tag:Nn5MfxKviTkNGwkP4uIQMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL3R0M0V5Qy9BYWlSOTlo
            ZlJ4b1ZJSU90K0lqektwTmxHVUY3QU0yUEFFCkppcGJ5UVJKYVUvQUxyMDdjTnk1
            UDB6UXVhS2I2TmJtUHVSUmpVQ0hVTmMKLS0tIHVFOE9IdXpkQW1Vc2V1ZDR1bmo4
            dDdCQzFpR3ROWHcreUhwSG4zZEwwclkK5HVXouawKhuUQrpcrsk8PaZnKw+mnsLI
            QzsJNEuOSuEAsThJkQaPN/c2Y1nH0rNyQ/YM70e9OWIWZteEPQ6ObQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:20:33Z"
    mac: ENC[AES256_GCM,data:7A0q4TLlM9rXEZw/dqjTSd78ZrVmU7LMHZTZQ20G9Sg15itN8U6sMXTX4y6D+b+QKWiKqIp6YnYK62rpZCy5y+NjJVMtNaE7Bbvo1JTlIhscr1xiIAcecyQyZhIIoLGXe8ZHmWEfDBM1D2VFCG0ifwPewWJtewLw3B9P2qVBnsM=,iv:++p5HLwUNGFCAyLtD1pxvmt/JBAEnDVt6/IQqYk4GZM=,tag:sVCq/dcIOhoZ4HLwYFZjjw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
