apiVersion: ENC[AES256_GCM,data:7WU=,iv:0lb+YsqXA7m5JffKliHY9fY8h693/ThQAPP1XcNe57Y=,tag:brROCE0ofzEPXna3GGa9Vg==,type:str]
kind: ENC[AES256_GCM,data:060Hq6cN,iv:0xjjt1zZye5+nSrkvPL8VF0Zis+cqlZ0OgoWCG6aBIQ=,tag:KHFE7iAKnIMcgJo1O7JOkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CvPPcgUs3ys4e6zi0liYYkXT3KY=,iv:sSPf8OIzsgxZlgN310166fURK25OT/s5guFWp3QpB+k=,tag:rLX3R5l31OoUA7pnsWc5zQ==,type:str]
    namespace: ENC[AES256_GCM,data:AJbiw/F95EmDag==,iv:H6274RyDKkWaGdZpJDzEWzxmhduXBaH+pmIsYeGSQ6Q=,tag:LjzmhgU47feujq9C0Y6JDA==,type:str]
type: ENC[AES256_GCM,data:97eZwwQ/,iv:5fOCHMvN8bLwjLsrUjVsrJS1dJjD107rIgm4BynzNaE=,tag:CoyR4BYNeheIdN0noX0laQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:LJzr/ZE=,iv:roQHC9BqcJc9A65w/OKPMhrshzhJpUG/GqBr+jdMdEc=,tag:t8MOTdhTF2qcOVgmn/UoqA==,type:str]
    admin-password: ENC[AES256_GCM,data:68KonRSiA3wUikYv1Ue4vpkhMb4L0sE+,iv:g5CKpuAotnXYLwDtYLw4ye3MdfrkUaRzN5SL6d0VG7A=,tag:Nn5MfxKviTkNGwkP4uIQMA==,type:str]
sops:
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL2t2VmN5STUwV1F0cTA2
            VFdvS1pHd3pEbGZXZmc1MVFkRllyU0R3MGc4CmNMa0JZS1J2VmdjYzJuV1ljN3Zm
            Y1JuVFpIVTFZdXNvRXFxSEhkWFZSRzAKLS0tIEs4N2pPbS9ISW5GWlllRE9JNFdN
            d2w2TWU5cC9iV2ljYlBVZXI5YXBneFUKXI5HBko5+usl47JwL8vzgnStlinH0zx/
            y/97lhFeI0SfchnwUvYONaLJ/rB9SMioRfdf5xwgVs4aD7JbJO0K7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU2RXVy9XbjNmQm9makpX
            YytMeHVYemU4b3NpeDVTVk1pd05DbWdsL3pVClg2djNJaVdQSnQ4V3o3aTRQU2Ev
            cG5iV0ZjTithK3dldnRUYTVsNHdiMGMKLS0tIG9qY3Q2ZjdRNHJKdWQvaTd1RjlM
            S1VPa1NhbTN1NmY2TGRPLytrVFFudGsK+RgJuMZtiH/t96JGxWRDqgdBcm2bcrUl
            LkYCScm+uRBUQf3Pw8TKdpPQu29x+wy4fXd0ZOUilqyMSgFN6EXsow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzL3J4K2R1VDZsa2RyOFIv
            NSsyRmZIeGdpNWhvSUZSN1pBTFRROUNWYVdzCjFsT3JoamxiMG10WmNPT3o1VnZi
            U1FJVUJRWTFiMWc2ZU4waGU5OEVWSVUKLS0tIERLUmI2a09Xa1lBaEVtTWNURmEy
            UE1GZHFnV3ZwdGZlVTVjME0wRGtWV3cKXbK2zNA9J8BAK0/hkVLKok6tgPuziM38
            prSTriOUFEOrf5zyCMsMM9TWOAZXPOEvw/iiIR7IKiOr017GrdUZKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZ2pKMHRuQXF0WnVDbDVq
            U1dqemxMYnRqd1pDSVVsVzI5THAraU80VWo0CjMyUEtIQTFrR1ZzVDB3K25saW5y
            YUtZR1JNSEo5dU5PSUdPK0M4a3RiZHcKLS0tIGhmd2ovQ1o4WGxSbk1yQmRlRGdu
            SlBrS0xUNFAyU3pNS0JIOUFCK0dhSncKCXT2DkIpZG7p8WhFyzoiY66r8Barzzg1
            J5CoehSbnVF/J0ks4xEcF04WGJR2Ay8nxRczccrgZnWnOP12U8I/sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:20:33Z"
    mac: ENC[AES256_GCM,data:7A0q4TLlM9rXEZw/dqjTSd78ZrVmU7LMHZTZQ20G9Sg15itN8U6sMXTX4y6D+b+QKWiKqIp6YnYK62rpZCy5y+NjJVMtNaE7Bbvo1JTlIhscr1xiIAcecyQyZhIIoLGXe8ZHmWEfDBM1D2VFCG0ifwPewWJtewLw3B9P2qVBnsM=,iv:++p5HLwUNGFCAyLtD1pxvmt/JBAEnDVt6/IQqYk4GZM=,tag:sVCq/dcIOhoZ4HLwYFZjjw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
