apiVersion: ENC[AES256_GCM,data:KRw=,iv:T3X/9K+Gl2B6a5+oun2/7oeMjspkht9KrrbEyvztAXE=,tag:wyjjS1S5KzQpD9RipVFNfQ==,type:str]
kind: ENC[AES256_GCM,data:8Q7yd5CN,iv:FGtzk2+9g0tvOtyJ77j1VOm8HRk0WpO1qFEAwQ9ds88=,tag:evdMSOt1F+FJznMIP98ZJw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5eKACR/RpOFctq8e8gcL,iv:NZAPKoFZPAj6eG5kgZmCPXZ0juDiB7IZDfIyeUFNtL8=,tag:rs8uoVGY0XFy9+P4FHppaw==,type:str]
    namespace: ENC[AES256_GCM,data:OsT/OPEtyw==,iv:W44fiKxe1FCc5KMgTbkAveZFjVlwPUeJ1O+USdZWS6o=,tag:hmXwPGLq4glim6lM9r5Ntw==,type:str]
type: ENC[AES256_GCM,data:BJ1J/09d,iv:sCLq5isTiRQ92n3QeGxv/CHu4N6YDxg7DH08L3hVNEc=,tag:XdH3pUdeiH8A6mPaWofvEg==,type:str]
stringData:
    dbPassword: ENC[AES256_GCM,data:4jUjD2iXYYfsaitUoW8obQSTpo8mHfpmJ8yil/uQ3hI=,iv:iB14qw3qDE1GIIwh8Eb1jDnbfOx9ctwsjMJEHoxEat0=,tag:3fjK+1uPakW84Ig26R0T5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSkRlWGtMamU4RzNZZlVl
            ZlFOb2d5QkhxQStvL1BjMGJvTVQ0eS96OWxrCmsvQUwzdGVXM3UveTFmTmZFaHlK
            Sm9aTjU0cCtJajdGV2hGa1RaZFU2QVEKLS0tIHJqMlRFaEY1SVd4SUlUUlZqMytt
            QkxaZFkzZVpRYTltSGoyQXVnRkFDK00KzXelPVOVdezNzPESrn+qEIhFbdIXYO5i
            RliT87t9cm5nkHNX7mM23klDD1qBJSQ2zl2WH4pQ5HvMJwJVLRf6sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:20:19Z"
    mac: ENC[AES256_GCM,data:F7x9oht/P7hlLbCXmXlsp58iI3Ao5w+eNvdpQDO/LKQCEbSu8UhP+9182DWNoB+NycbudaxaY5CsaZacFq01Tl3GNi6HHDHjgeruLRyaE4n8F76Ot7YbpGIeVQpStuZxGY4wLfTx+BUQnwtXyYJH8Ve0a7h0eCq8aottYmLk+bk=,iv:ogXxDkRLhlV/x197J9ZNFCpOL2h1Su+0Epase8GXceI=,tag:nZSRRpx6AaZ9v5IABKaWVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
