apiVersion: ENC[AES256_GCM,data:urI=,iv:Geox7cAYF3zKsmBayLsL2Pl5Pn4L4PKPDohB6Vn1xmQ=,tag:vfyEnyhw1X4vJ1bjnIdNfg==,type:str]
kind: ENC[AES256_GCM,data:aoL5vvpb,iv:l7xlH4fUgzulPsSCxpOtIi8XIO7JoZygmfRhgSm1Rkc=,tag:c8zsjn6Kmea+DdpkqxF+5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:aoVjkHNLM67Eyg9Aan+qZEce5Q==,iv:cCTE3Ox3V+EFPd8F8mT7gNM4CL83r0UzAQBdbuFR/Rk=,tag:mum+iCPw1aUdgTHU0bJalw==,type:str]
    namespace: ENC[AES256_GCM,data:TcQuW6XexRwwzy8=,iv:DSStdyfwPfSmTpG9efh33wElyN2YU8ZmwYUv5NnS4Ic=,tag:kDtp0yOa01hUs1ltcqSFNQ==,type:str]
type: ENC[AES256_GCM,data:FEDNC/D4,iv:fR/OLWNP/KQ154wV/ZxVBi/4k/Vz9cXR5ifPzpB2LKY=,tag:+hnlBZGfCf9+I2EDVGioUA==,type:str]
stringData:
    adminToken: ENC[AES256_GCM,data:N9XxcMWdd5brUVDdYLOyxdNr8ptFFURA4qpydB2xwUWQ6s+Wb49WzPw769xxPscNvaAPKdL2FyRqgIBKDUfggA==,iv:UYvTGZ12ZPVTiMfoa/dNxVPOPC1kWT14RM8oXQvuL54=,tag:yODAT1NunpqWwvbM5lNZkA==,type:str]
    smtpUsername: ENC[AES256_GCM,data:WQYbEyrBJIRU75dvIwmq6JOgpCoWwHYi,iv:CS8sOqaXIogdLABfhsxmlw9jy79tMnS5n0BW/WoA/p4=,tag:OqvPDhF+KsAv3C7qPpRO0A==,type:str]
    smtpPassword: ENC[AES256_GCM,data:I4x9Ghn+XTehb4YhgQkeam1f/yfW+qfzEDaybQxBT3CCS9MrT0gl/NABg1/asEbZz8c6t7xXAbT40zFQdcDbww9xTe8y6Sgvcpge7Ik9J2ps3FemMZeEhN6z,iv:CeAFIhqXqwKSdeu4fC43UC/5vqOqM+RuwMuYRmo+KJo=,tag:p6lXiZL6yKxopInuKi/9Zg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT2hDeUhoejI2Wnp6SEJO
            cDRBWUFBUHRKbVRVZjNUSEJGTjZEdzlFeGtjCjVjbTc3NFFicnlpVjRUM2JHcjFJ
            aVRSTnNDZHlyNUVSQzVpZ2hqNnVaQTgKLS0tIFV6WVZucFh3NDZIY1l5OHJVVWMx
            QS9XMjI4WjNLWWhlY0NMNDFhNFFzWHMKggbPSrgTskKUEqvaI65oecXygJFXA0jN
            xsP76tP97RuOS8S3xDhtAF1Qkl+7iMozVHB6ONASjDY6y8ZiZF1QCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWnoybGlocXhkMi9YaE1R
            ZTRUMUM3dmUrcG83d2hsMEQxTEI4WFA2V1I0CmpqdkdFV3VidHg3TkdJL2JBYmVx
            NmNjTDRocG9kNFZrRk1uSTJ1RExkdTgKLS0tIEsrTGZrVEF1MDdsY2RCSzFrWWc5
            VFpsQ3FOU3U0U1JZWm5YOWdIV1Y3UDAKiLlMsZv5l1W9lgoznI6yNSYRz7UmrmAh
            naKb6wYV8ep5rHCy2fytY7ojtE7AUqWDWjthDTHzuLcs75/p8FWfOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeERhWFZjRkN3RlloQnda
            cVFYVm8wS0ZNZVAyb29SMXY0T1pwN1VLMnowCnpscXp4aHNOeFBkaVVGNHhMOGFO
            ZzZhQkRBZzNjU3o4VTdGYWJaVmdCRGcKLS0tIHZFZ1lmUXNJbXY4bmdSdVY4eWJI
            b21VYVQ5bStDMGY4dW9oYWxJd2tWaGsKVfzAEuR3ojktSH4JWJQWgzdgf1Ws2sQh
            Xo2T304Ps+JUvORpo8VpLimpiHzV7eLs3HL8f1K9qR64358fIcwcqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaitQZjFkbkh3ZTM0RDB6
            WE9RVWlDNXkzVXZvYnNIZXNBcFlmM2RlMUI0CmRlSzQ3TXpWMTBVNmoyaTBCU0tD
            R3VhM2YyYUdwWTNVTEVubEl6ZTNJdDAKLS0tIFBRTHdqTlhwNXhGRi9kYUowNEtH
            VjBvWUFxY3FDblpYYXp6Y0RlZ1lRcUUKGZ/3q7Q1eYCvJpMYdB0HN2g047n+MpYf
            CeL84Yzt4wlsl10dhvtURtdplnrZn5vV7RtqQnybDDTJEQea49eIPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T16:37:53Z"
    mac: ENC[AES256_GCM,data:rK1CSBV1LYFRVpIR3ASAmjkCsT9R3RslNDlCXj5VLEN+dt1xnEyEfK3OOYGd2I3mrEwwnC1SjDbdmcFmT1/C9kH+qSTFNOALDlzYgEjm9eJGA6ELDdydhIYOz61NXYtdvBp6gNBmEige35YQtNZKcLgI82aJ+OsNVAAobkEyHXk=,iv:elm+bLckgJjhA1E679nN9gvHvc8SoPOufjal/Lno2mo=,tag:9qBwAOA3EO+nu9wOwAwimg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
