apiVersion: ENC[AES256_GCM,data:9bg=,iv:S4p7XRAu6Jz3qrPFMyTzqbLm5JlsHV4TzBqak1rzyl4=,tag:x8eJJSkcTJ2saXkH9dNf2w==,type:str]
kind: ENC[AES256_GCM,data:vd/2C7kb,iv:1krFtSsNZiD96C04HfzmBMm4Bwxw1YSffqUgeKPu24E=,tag:J0QfaH2wM80jVN5SeMdL2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vvonKK8wdfN34bMLL2QOyQYNaQ==,iv:MgGMq+mw0m81dwiaO71KyAZjefqdXG7kNZ1W+zMsLrg=,tag:RpaDbxwHQhpH7pvNt3+w3A==,type:str]
    namespace: ENC[AES256_GCM,data:ojHRT5z/WMqVAUY=,iv:Khs2IlVpVssTh3gIptsiDM7Cp4UlA65Fb+RhaI4tBjs=,tag:vyUQYvixR0ETnyh4Qilz3g==,type:str]
type: ENC[AES256_GCM,data:Q81fqo+x,iv:kWqMD1ZJ7cxo/zLJwBLH1ChywOvuHnglvDBQHB7zD7c=,tag:njS5jDDw1nSoslLtEjK5Ew==,type:str]
stringData:
    adminToken: ENC[AES256_GCM,data:5D8UC6VQcc0ykMOjssjTLMrT66qr7piTuGMaFgijqEcYRYODcDS+pusbr7xGBPBQgIi5iMv6kDW9QB6k0jQ5dQ==,iv:ziheveUL5ZPnkpsN58+gXo5+MVcPaqVPK97ZT8/BE0M=,tag:S0dNxhUhcNCjqdPE4bRRJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRS9reWMveUVSVHNnTVVT
            ZjY3UXh2UHpZeEtWZ2k1UXIydTFFY1FRNVd3ClhBZUNLUmI4Nm0zMmlLVjZISUVW
            L1ZrN2ZPQ2ZjVEk3U21uQ3dSSlZNMUkKLS0tIHFrV3lvK2dvM3VsZ1BZWVhPb1Fu
            RWFBcVFhY0NxZTFTVXNoS3EwMG5mbWsK0r659asRGamGpdVy+C5FraxewwSyQw7A
            +y4yKjiLnkJ+0tVvo3Clf/Fsnsu9qEXM6K9KcB4NQJhfXDPoNaUbvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:20:19Z"
    mac: ENC[AES256_GCM,data:lcTsqC/53evjwDauGwa15R+ZI+VUIy2/4cejuPWVKsbEFW/hxvLml+ywguRdth1VC2iBLOkJWWTciDxuaZYyc8WuEQngg79aaovQt8HsmFpDXBUiDIalO7tbrRmOIYy+IoxWR0rE9mUOWCR8wxfC/klDBnmEZK192jjYRBfynyU=,iv:ArSU9jLiURxhY93FiworQPtHEoq0aWdjBDWCe4MIhbw=,tag:55rWUEww64c+oGTW03cQwQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
