apiVersion: ENC[AES256_GCM,data:oJI=,iv:OoWAsCQTdQsETOwWz4oDGHfy1QjfHOKdHQszr6+tYwQ=,tag:r9mh40aC/lfK/1LbpVXsiw==,type:str]
kind: ENC[AES256_GCM,data:b/g1RzFk,iv:snBqIcJX/a9iUFxYPvqmlal+Cfpkg7ndamGbBLK1qoE=,tag:AVCtdvjRbkmZJSmnz0dgJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:A2ouQz8j/FSjyzER2OPtUJewslU=,iv:FS/wksYB9RZst6lcS6oWe5IAAOmear8uS5jWD34+WKw=,tag:PeMKJ03kJi/gQn4VaaaZ+w==,type:str]
    namespace: ENC[AES256_GCM,data:fqnsA6vK4pxUfPgR,iv:GW2oBHEus76SdebnCx5hYBsJRH7P1kHjpqeotxBb9KM=,tag:yMoDqFP+W72/IGUJPVwptw==,type:str]
type: ENC[AES256_GCM,data:I7cFR26s,iv:2sZr+8rgOEQyfREyhrz1Ky49UHLHYMZ4KfoECTQHIeo=,tag:W3IhqpyCVupo7lb3rDabpA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:5MZ0qg2Tm0uzdsyWL9xePK5hWyWlvtoybC7sr9rhNcVgIw==,iv:EqdvRPRl1vOVW+YgpMk73rmmPN0jnlOBXqaEnyQdNmk=,tag:VaNa8aYN06Rs2biA/2bevw==,type:str]
sops:
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRG0zdzdJNVNQODZBK0tX
            cFl2V0dwdUdlRDVuNUpPQzdLS2kxVUI2VlZRClNxWXJCVTJCTkRYMjI3eFR0aTg3
            eVgrTkNIamVWM1NqRlNKNFlwQk8zWlEKLS0tIHRYNWkwL3ZzckdUbHVXTWpCTUtM
            S0pVZkZUZG5lc05GcnpqaVZ6OEFTY1EKJ6McBy8Bb95zeRuNnFSXigFaccUJ4pnq
            3jVK7cHi/Ap0SaXl0B9FD5jvxBKY7BfwZyDoErScwzOPSFd+16+rHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcHNnaVFobkJPcnNhemxh
            VGRzblJkVEpEZDZGNGQ5L0dhbmFiQlNDeHpNCmFMZFovQWFVT2I4M3ZSbk9VQWZC
            OFU4a2wwRTRSdkRuZHFYcHM0dG1EaE0KLS0tIEN3UTRmTFhzWmRCd3Q5MWRDMCtk
            Yk00VmlDTVlXSER1Zm9JN2NEa3NkckEKfiJv9BME3adk2QpUmw9umTO8UqqqOdn0
            djAhO1WzleDMIYrVbcR9MGe7YWGIRnKFzKOxoF1pW14pxCmcmmtonA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZE1MUWdBTCs3dW1EZ0RN
            TVMvMFZVcHAzQktvUzZuZXFFb005T1pTV0RBCnFUWHJZQmp6b2t3V0E0dDdaa1Rk
            MEYxQlRLeW1xTytGdFFBNG1UcHlkaVEKLS0tIDFGSGY1eHJRRlE1NmlrYlExYnJN
            VWh1MklUbDliZnBUVE5ZOU1HMUdtMDgK9WVY7clbbUrocmNdnRR7qpl3fulLL2HS
            cBzdLrC2wCVBHSa4n50UvZB4JR48i3gb1NsSHqHRltFiNcYew+FwGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZem54cEEyMUNpVnJiMW5r
            S2FPSFdGL1Zoek9jSU9jbk1GbUVUUlJuM0VjCnVWU3V4V3F6SzBqUFVFTmxWVW5t
            NkFsaDl0UGtvSnl3RTZtTVdXOUtLbHcKLS0tIDRRbmtNbEFHSGc4cHVtOFg0MVF1
            NHNFS2Y0eHUzeG9Hc1BpSTRqWGdyU3MK1dB0gKF2r0CeAzOho0Uouqo4ZsKlbMti
            0PkkJeNuAE+SxZ+xWlLc85ibhS9KA2V6LJcv0jFOhMmGRv2ltH5yVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T12:45:19Z"
    mac: ENC[AES256_GCM,data:CJr5kQ7b1JcFKoD43+tsiwIsqXvgqc18k7Prvg7HMpBS0nlaVE+jSOvjvSGpo/G49sCNsQerjjxtURfZt0bBqlzNwZtqQGypuzAXYojdSQ6J+f3NTAq1T1F5qoAiHBk4hToDpWWsCjEdSrhms8JWw3nvMJQMXMQ4JZ8/iz1ZgdY=,iv:Q8dUYCrK6TPXgKRRTF2c0oX7DnCLrQtzA0XqIgl5Z1g=,tag:wmY2LhSXypxYr0iW6ifRcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
