apiVersion: ENC[AES256_GCM,data:4As=,iv:pRbhjTa+meEh1HgOBeH2CCdYcegN2yzLzOfxyGQY1tI=,tag:MApqAlJPoTgsh18OXMbUgg==,type:str]
kind: ENC[AES256_GCM,data:ym3kMqH0,iv:0LC6d1DtCOamS2WwQBRAHmNCx6HCAf2Kz26p4f9FFME=,tag:SSWWLtKGDCj0WUq0SqZOvQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yflDvbyI/PMcRYmL24aG3xlZCHM=,iv:l1kKGofKh+TJnuQ6t88i23VrY7EaQgJEx7SrBo4uoAw=,tag:3JnYQVfv/lRm+Xm4pjDzGA==,type:str]
    namespace: ENC[AES256_GCM,data:ep/VNoRqkgDfSI5S,iv:Zp6D4uU/nhdvzcQpvSr0Nw2I74DAOB9Zy9AiB45AyoY=,tag:6Cy+9bR/v13HtEvDV5pfEQ==,type:str]
type: ENC[AES256_GCM,data:AXHvFoah,iv:O8xufHrOhKY5C1/CS3nCLSZ72BqF6aL7XDCw60GAI5w=,tag:hR+JIYvIBBaf+k95mnCXHA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:5sxjlRMUqMLleTHPka+4EW1jvgx60uUfVjVROV6JIsMCm05zvt6BI1ybRzo=,iv:+OZ7iHjSjnZacKcBy0gzmRnhVFWQQDSiddFYBtCjRsI=,tag:Ab6P3lgkSDX7pqR04hQSIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRGV6RWlyUjUrbHkxb0Jt
            MG1TNVhUQm81cHRFT1ZMN3hoZUJlYzVwVzI4CnBnVWR0NEZMMkl6MTcrVUVCS0ZN
            YVdUa3dlY21keHZ4elBGU3VYZGJRNXMKLS0tIEduR0Vid1A0TlFoTHlKdkFlMnBU
            akJpbzZTaEFua29RWW95WTZnZ0gxRUUKckh2QGRh0h1vsE4285TmQTPputR6V9HY
            rmwEHsSGf4gX4rYRImxTjXC+buMxxxvJ9r9Z9rT1ie8yGYoTaj6XTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:20:19Z"
    mac: ENC[AES256_GCM,data:DK+vfxgO2I+3YJLhTgR0tGSOj9+ogyfghq4NwRSk2rW267r/ooRT8Y0Cmatts0ITSSuEAntYtwF9ywpy6ZDQtoJSPPLJ7ofmnzwP09DHIp6imBy7+fmENFxhES2PUMFvegUWJHOfZ2fi5nqtmsZuvbTNJWrfNfT9pk8a+AH42K0=,iv:D/eDpMz009vesU74DbX84nZ8TsbOoAexQR4DVmvQBv4=,tag:fd7kvkqg9Gt4j6IWWlLa5Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
