apiVersion: ENC[AES256_GCM,data:4As=,iv:pRbhjTa+meEh1HgOBeH2CCdYcegN2yzLzOfxyGQY1tI=,tag:MApqAlJPoTgsh18OXMbUgg==,type:str]
kind: ENC[AES256_GCM,data:ym3kMqH0,iv:0LC6d1DtCOamS2WwQBRAHmNCx6HCAf2Kz26p4f9FFME=,tag:SSWWLtKGDCj0WUq0SqZOvQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yflDvbyI/PMcRYmL24aG3xlZCHM=,iv:l1kKGofKh+TJnuQ6t88i23VrY7EaQgJEx7SrBo4uoAw=,tag:3JnYQVfv/lRm+Xm4pjDzGA==,type:str]
    namespace: ENC[AES256_GCM,data:ep/VNoRqkgDfSI5S,iv:Zp6D4uU/nhdvzcQpvSr0Nw2I74DAOB9Zy9AiB45AyoY=,tag:6Cy+9bR/v13HtEvDV5pfEQ==,type:str]
type: ENC[AES256_GCM,data:AXHvFoah,iv:O8xufHrOhKY5C1/CS3nCLSZ72BqF6aL7XDCw60GAI5w=,tag:hR+JIYvIBBaf+k95mnCXHA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:5sxjlRMUqMLleTHPka+4EW1jvgx60uUfVjVROV6JIsMCm05zvt6BI1ybRzo=,iv:+OZ7iHjSjnZacKcBy0gzmRnhVFWQQDSiddFYBtCjRsI=,tag:Ab6P3lgkSDX7pqR04hQSIA==,type:str]
sops:
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aGFDK2xkVlBuaVE2YnA1
            TlN4aUk5cUxza0NPUFRtT21ybXdrMHRXTEVnCjRZTFpRRUVOOHhXWEZUNGI5T2k0
            TG01dkFpT09SeXBLTlMwMlVzaGU2ancKLS0tIHhERDFvSFNOUHdIcG1wU0dSbGxy
            SzliSDJRd25jSWd1Y1RaOE02UWhZYXcKvw7PUS/AusM04A9G1WahLycKctsCeXpZ
            9nEJJ/H7F/TlHePwqqu0CFtNTyxCaEYGvZ1VSWcAb2v5Kd/alBXtAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TVlkMGtETURGV3RUWEdx
            MmlGcHBRN0tmVzdZR0NPdG10THJyc0dTSGs4ClVhYlIvUTR2KzA3bkdwMHlyeCtz
            bUNWcGRNenZucVpNanZSaFM2ZHJmeGsKLS0tIFlEaHB1czVrRGpoT3BQL0ZjQlJp
            YkpKS2xqLzV3dFJTdGdsamxkSXJORnMKAVqK6Al/QktTU1n8jl6uWG70CpI4DifN
            q3VI4LOKOq8zRrVlE+tTSdZuoqCWhLXFf1Hi2+HNyjU5ga6bSJbyrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:20:19Z"
    mac: ENC[AES256_GCM,data:DK+vfxgO2I+3YJLhTgR0tGSOj9+ogyfghq4NwRSk2rW267r/ooRT8Y0Cmatts0ITSSuEAntYtwF9ywpy6ZDQtoJSPPLJ7ofmnzwP09DHIp6imBy7+fmENFxhES2PUMFvegUWJHOfZ2fi5nqtmsZuvbTNJWrfNfT9pk8a+AH42K0=,iv:D/eDpMz009vesU74DbX84nZ8TsbOoAexQR4DVmvQBv4=,tag:fd7kvkqg9Gt4j6IWWlLa5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
