apiVersion: ENC[AES256_GCM,data:hgE=,iv:IykdhFukvMZoKHPmh9eG0guoXEEFJaQCUF8/P1bOmjc=,tag:zta/NH2R8KaM2MmRTMTbEQ==,type:str]
kind: ENC[AES256_GCM,data:zqXxvmgc,iv:nvcVhlsc+BFnWQCWp2NrlJ1wbVEPFr/m2xukPg0/OWg=,tag:knR7t7BhzPaJbtotRh0j7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PeGU96fCCAkT7zv2Vg==,iv:+OWqziKGLzfPhllkVW/MHPbQ12WPLS6uvkpDk82I9R0=,tag:t541OS0BVVEM5KRUysVj3A==,type:str]
    namespace: ENC[AES256_GCM,data:GSvpamc=,iv:7A0lAU12GUHat23D6WSM9Q5boWzqpj+sOgf/Tp8tOFM=,tag:Iq4FNxVyJ9/X3CqrTIRkHw==,type:str]
type: ENC[AES256_GCM,data:qOa/zfKN,iv:yuKL58i9z8iajJbrM/HTsLULRFzOeSvKf6kQJgjhXqY=,tag:lzeUSlFuKjriN+bgwY80Fw==,type:str]
stringData:
    dbPassword: ENC[AES256_GCM,data:DpmGZSsLsCnQXi4DQNcwM5pf/heBMBOSVsoFiQzaQLg=,iv:iK6ER2X+13/MfaOKgduZkFNdrtRk8nH6ltftRyb2osw=,tag:HHxxcnIaBffilf9iHibPLw==,type:str]
sops:
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRTV3UUdBV1NNL3lpeU1K
            WVl2S3Z2eFd4NGl6SnBnMFR1YngxaTRHTG5jCklWTko5MTJObElFb1l1MW5oTzlI
            dzlldnQxMHBjUTJMZkk5TXdZOGZWY2MKLS0tIGdLYzNpV2R0L2twQjhiTUhQWWVj
            U2cvNURnbDNnOUpkZ05TcmR3Skl1WlkKJi1IJl0JzZlQ7gyudPiecv1MXqhxMVoP
            OlDF+3dgggpkKfcKa0tkzWRFva8ELpHkausCbwXYuYH4Vdz3Yks61A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZGVOKzFINk1nQWRWSk5l
            UnMwYVFvSURqTzdnSmRpaE85YTN5WVlQTDFJCjVOTnhHUDd1aS9xc2pjQ1lhOTVM
            dUdEYjFjM25UREt3eERVSFlmWkxJQlEKLS0tIElmRStHcjdJbE9lOWx2UVdOMGpI
            K3ZqOExubFAvd0RwNG5vWk8ySkxsSVkKCnDccqhDoP59vTe402LH8rli6xNY1zhY
            0VTbXddTNgR36ZCvCQ8EDNL2MlYE3UvwPH0Hd2jGAJTf9cmVfFo1rA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY3Y1RmVUSTR4TzN2Y3dH
            bEJTRmZnQjJCcVdYREhIMzQ1bXFMSmJ3REVBCk1CdkpycnU4VUdBTDF3SEl6OGJt
            a2hWV0pkdzNPM2o4UVdtMTJKZDRlVE0KLS0tIHhnaUM2R1d3UU13eVJPem5oZld3
            YkdPd3BUSVVPa3QwOE5WSElpY20zTEEKeBpLG1iedRLN2XfuyqiSnBXeUTeZoWef
            ceDEEAnGndyv+hfPKYEVyBn3+nZpIeXW8zIiwk3tbWY9/8CpaZfeBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age185ef0fqjnpf2yr0cxlyral7kdfltsckq84egtj5fkjjdm6wn35uqm0tu8y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZlVrYkViN0VOSE9DVjJW
            OWlHTFl4M2NyTnZZcElQM2ttUDNFQk5SRldzCnNFeGtSWU9JbG82eVk0OGRGSzlC
            RTV2TDBZRjRrbXcxbVhtZG15aTA2MTgKLS0tIFFiZVNOMmROeEtVT2lpQ2x4UlY4
            VE1QYkNrTFJRaWZBZ21EaHhqSHYwMDgKO+c4VSgE8sZqRC1SEvE4tC+ofcDqBVJn
            8Or81meo1TxMTphq3GJq65WVDSKO27RxWGjIDimp0xj6szgjycK2QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:20:19Z"
    mac: ENC[AES256_GCM,data:RGodsO4TaBEmtOlldxjodm54jdSgBDA6f0nYB3mAuzneZe02HFFxlRdtdyKO5Pd2CroG9nlUlh6FYBeTHnvl1gNkENoVqQz0zRpgyUHqX0EYlr3C1HzkBJD6oE4PEto1N9FmcDJhgJelNE6FtEl2V+Fws5yBUazKkmcuvCLcvac=,iv:XtYkHfM0Zo+wHww5my72RIqLW/1v05S2YAx9eRYgrQc=,tag:z660uwVclt/ZcksNyt0vUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
