apiVersion: ENC[AES256_GCM,data:hgE=,iv:IykdhFukvMZoKHPmh9eG0guoXEEFJaQCUF8/P1bOmjc=,tag:zta/NH2R8KaM2MmRTMTbEQ==,type:str]
kind: ENC[AES256_GCM,data:zqXxvmgc,iv:nvcVhlsc+BFnWQCWp2NrlJ1wbVEPFr/m2xukPg0/OWg=,tag:knR7t7BhzPaJbtotRh0j7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PeGU96fCCAkT7zv2Vg==,iv:+OWqziKGLzfPhllkVW/MHPbQ12WPLS6uvkpDk82I9R0=,tag:t541OS0BVVEM5KRUysVj3A==,type:str]
    namespace: ENC[AES256_GCM,data:GSvpamc=,iv:7A0lAU12GUHat23D6WSM9Q5boWzqpj+sOgf/Tp8tOFM=,tag:Iq4FNxVyJ9/X3CqrTIRkHw==,type:str]
type: ENC[AES256_GCM,data:qOa/zfKN,iv:yuKL58i9z8iajJbrM/HTsLULRFzOeSvKf6kQJgjhXqY=,tag:lzeUSlFuKjriN+bgwY80Fw==,type:str]
stringData:
    dbPassword: ENC[AES256_GCM,data:DpmGZSsLsCnQXi4DQNcwM5pf/heBMBOSVsoFiQzaQLg=,iv:iK6ER2X+13/MfaOKgduZkFNdrtRk8nH6ltftRyb2osw=,tag:HHxxcnIaBffilf9iHibPLw==,type:str]
sops:
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdDlKSUVESG5oenZXd1Js
            Z1U1QUNNbnNQUC96WVZHTi9wY0lOMEtySDFJCkMxSHY3bkRkZzBSRlNGeUVDNWJF
            VnUwUzhEVzd3dGo1bG0wd0ZOR2QzYWMKLS0tIFgrTEZreDlOc2Y3T1BiaW94QVlT
            UVo5Q2xtQUVGcDdJMGlHaEloOTBaMlEKDnGyjJ3boAQXzGdsqEdz0eFMQa66kzHd
            hb/X+0SWi2xnF77Bm87X102WTlPoV+TJoWlTiBMw9UUgQjY5NFq5GA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESzhYTU5mVHV4eUh3Q2hi
            SUtVSFQxb3pEdnJnY0xJWWRabjFRUXdNTERBCnNZR3dCV0VtNUJHODhnYWRxaERF
            SFhGeEFldHA3QlE3a3dxUm9hckV0S2MKLS0tIG9QeFhIUTRpekVlNStDNFU3ODZZ
            Ni9EK1JySHFYa09jb3Vrb2lwWHBJSmcKzTeQAEEnTm1FP1U8GA55d+DDHZqsuczg
            yXXrRptws/xFaGlPtb1MTkDDp5wL8GWjmRBxguz0jbQGoax0nZsQkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:20:19Z"
    mac: ENC[AES256_GCM,data:RGodsO4TaBEmtOlldxjodm54jdSgBDA6f0nYB3mAuzneZe02HFFxlRdtdyKO5Pd2CroG9nlUlh6FYBeTHnvl1gNkENoVqQz0zRpgyUHqX0EYlr3C1HzkBJD6oE4PEto1N9FmcDJhgJelNE6FtEl2V+Fws5yBUazKkmcuvCLcvac=,iv:XtYkHfM0Zo+wHww5my72RIqLW/1v05S2YAx9eRYgrQc=,tag:z660uwVclt/ZcksNyt0vUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
