apiVersion: ENC[AES256_GCM,data:hgE=,iv:IykdhFukvMZoKHPmh9eG0guoXEEFJaQCUF8/P1bOmjc=,tag:zta/NH2R8KaM2MmRTMTbEQ==,type:str]
kind: ENC[AES256_GCM,data:zqXxvmgc,iv:nvcVhlsc+BFnWQCWp2NrlJ1wbVEPFr/m2xukPg0/OWg=,tag:knR7t7BhzPaJbtotRh0j7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PeGU96fCCAkT7zv2Vg==,iv:+OWqziKGLzfPhllkVW/MHPbQ12WPLS6uvkpDk82I9R0=,tag:t541OS0BVVEM5KRUysVj3A==,type:str]
    namespace: ENC[AES256_GCM,data:GSvpamc=,iv:7A0lAU12GUHat23D6WSM9Q5boWzqpj+sOgf/Tp8tOFM=,tag:Iq4FNxVyJ9/X3CqrTIRkHw==,type:str]
type: ENC[AES256_GCM,data:qOa/zfKN,iv:yuKL58i9z8iajJbrM/HTsLULRFzOeSvKf6kQJgjhXqY=,tag:lzeUSlFuKjriN+bgwY80Fw==,type:str]
stringData:
    dbPassword: ENC[AES256_GCM,data:DpmGZSsLsCnQXi4DQNcwM5pf/heBMBOSVsoFiQzaQLg=,iv:iK6ER2X+13/MfaOKgduZkFNdrtRk8nH6ltftRyb2osw=,tag:HHxxcnIaBffilf9iHibPLw==,type:str]
sops:
    age:
        - recipient: age1m483x92dqmkazqx8xu7xc8waw3uh23a890uv4tcj6d4xafg98alqq0vqeh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eFN4M0dXODlSLzNDNkNi
            MFdUb3hnbVFUa2lYQ1QvZXlaT3NrSm5SdnpVCkFleUdPbEdaQ1dpL2N0WlZHc3Vl
            S0tlOFJRUnJYZ3V2NUVyY3AwNG8ralEKLS0tIG1zRjF2eWNHdFpHTkNaMDlyMTlQ
            MW5iZ2xmTUhNdEhwRUtnM3kxYjh3cnMKqeC0FTsfbWI21jxofpd1pEgps5/H5TDZ
            xW+BC52epPtkzTPW9QWk3T+edJFFJr0fLaMQ/enBFhGpSbUxCDdI4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12ktgr3k30msf4ur4g8pknfzqhzh60m23dgtzketquzgm4s6kvvkq8q53x3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbjFpeDBLdlFVRWptSHNk
            MHgrejg0eElHdE1wOEpEaS96YjdlVWRHYm53ClR0KzRiWk1xNFg5RlV3TDBqVVlr
            MWhZVldDOGZKUDN3WVhmZnNtRERiYk0KLS0tIEgxdmxDUHVwQ1YzTUVZbVJvNjNP
            SnZ1bGhwN1ZSV3dCRXNCSkRJZllqYjgKfXtvuAv1SDcB0oh2gzwGKmYMeaiUb+Ip
            OwaI6uxEtmdWy6W8QxdZGYPPSKC3V13iV2o1D1BkRYbElx8dm38img==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age124fupdje6hjmj7zv859xekuvawsek9qg4z3cefa96dsxglglfcrqkhfzk5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QWVLN29vOWNRdkJkdTNG
            enVPSmhtTUx1aEx3bW5NcGVHQWp2d3RHQVhJCm5qN3R1bXgwdmg3a2RnRUNMdUZi
            enpHTk9WNXFFZE4wQ3k1ZmF1ZllxQlUKLS0tIEtoa1V5Q2VrdCtOb1NXZU5IOEZF
            TVBIdmoxcVFjVENYdHNUNmlWQjlKQTQKkpvrrtcJ9qyhmlGjYGvHEh8z0T0T64uJ
            rJZu5+jiXrkNLbNdEP0xl9qzEVgSNOGJQQ2CFx2rXEH/l9gbyNsZ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T11:20:19Z"
    mac: ENC[AES256_GCM,data:RGodsO4TaBEmtOlldxjodm54jdSgBDA6f0nYB3mAuzneZe02HFFxlRdtdyKO5Pd2CroG9nlUlh6FYBeTHnvl1gNkENoVqQz0zRpgyUHqX0EYlr3C1HzkBJD6oE4PEto1N9FmcDJhgJelNE6FtEl2V+Fws5yBUazKkmcuvCLcvac=,iv:XtYkHfM0Zo+wHww5my72RIqLW/1v05S2YAx9eRYgrQc=,tag:z660uwVclt/ZcksNyt0vUQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
