---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: silverbullet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yasuke2000/Homelab.git
    targetRevision: HEAD
    path: apps/silverbullet/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: silverbullet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
